apiVersion: v1
kind: Service
metadata:
    name: ms-a-svc
    annotations:
        ad.datadoghq.com/ms-a.logs: '[{"source":"nginx","service":"ms-a"}]'
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
  selector:
    name: ms-a