apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-front
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portfolio-front
  template:
    metadata:
      labels:
        name: portfolio-front
    spec:
      containers:
        - name: portfolio-front
          image: mohamedbenattia/portfolio-front
          imagePullPolicy: Always
          env:
            - name: MSA_HOST
              value: "ma-a-svc"
            - name: MSA_PORT
              value: "80"
            - name: MSB_HOST
              value: "ms-b-svc.ms-b-ns"
            - name: MSB_PORT
              value: "81"
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 50Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"